version: "3.8"

services:
  back:
    build: 
      context: ./back
      target: dev
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
      - TEST_DATABASE_URL=postgres://postgres:password@test-database:5432/postgres
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 4000:4000
    develop:
      watch:
        - action: sync
          path: ./back
          target: /app
        - action: rebuild
          path: back/package.json

  front:
    build: 
      context: ./front
      target: dev
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./front
          target: /app
        - action: rebuild
          path: front/package.json

  database:
    image: postgres:15
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -U postgres
  
  test-database:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=password

  adminer:
    image: adminer
    depends_on:
      - database
    restart: always
    ports:
      - 8080:8080

volumes:
  database-data: