name: CD

on:
  push:
    branches: [continuous-deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to editoria
        uses: appleboy/ssh-action@master
        with:
          host: 0923-orange-3.wns.wilders.dev # Remarque: l'adresse du serveur, sans 'ssh'
          username: wns_student
          password: ecopedia
          port: 2269 # Spécification du port ici
          script: |
            cd apps/production/Editoria
            git pull origin continuous-deployment
            make run-prod
